# Only build tags
if: tag IS present
language: node_js
node_js: '10'
jobs:
  include:
  - name: "Build on macOS for macOS and Windows"
    os: osx
    osx_image: xcode10.2
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - USE_HARD_LINKS=false
  - name: "Build on Linux for Linux"
    os: linux
    dist: xenial
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - USE_HARD_LINKS=false
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://github.com/Palakis/obs-ndi/releases/download/4.9.0/libndi4_4.5.1-1_amd64.deb && sudo dpkg -i libndi4_4.5.1-1_amd64.deb; fi
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ];   then yarn run electron:build -mw --publish=never; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then yarn run electron:build -l  --publish=never; fi
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then chmod +x add-osx-cert.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./add-osx-cert.sh; fi
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file_glob: true
  skip_cleanup: true
  file: "./dist_electron/*.{exe,snap,dmg,AppImage}"
  on:
    repo: vcync/modv-3
    all_branches: true
